### ISSUE TITLE
script broken

### ISSUE THREAD

**Issue by What-Zit-Tooya** [edgarchinchilla/aptoidemarketapkdownloader#1]
always get "404 Not Found" message
Firefox 50 with greasemonkey

**Comment by edgarchinchilla** [comment]
Hi @exodius48 could you provide more info?

For me, the script is working well on the following config:

Firefox:
     v50.0.2
     Windows 10 Anniversary Update x64
    GreaseMonkey v3.9
    Aptoide Script v8.1a

Chrome:
     v55.0.2883.75
     Windows 10 Anniversary Update x64
    TamperMonkey v4.2
    Aptoide Script v8.1a

**Comment by What-Zit-Tooya** [comment]
@edgarchinchilla Its firefox fault i think, because after update to firefox 50.0.2 script works.
closed now.
