### ISSUE TITLE
Script is Broken 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [edgarchinchilla/aptoidemarketapkdownloader#2]
Download button does not show on screen
https://s11.postimg.org/tfxn9dv1v/2017_02_15_093812.png

**Comment by edgarchinchilla** [comment]
What is your actual config config?

My currently config is:
Spanish Language
Windows 10 RS1 (14393) 64-Bits
Firefox 51.0.1 64-Bits
Greasemonkey 3.9

Apparently Aptoide has changed the HTML code for mobile version of the site, I will take a look ASAP, in the desktop version all works as expected, see below:

[https://s18.postimg.org/st2veetux/desktop.jpg](https://s18.postimg.org/st2veetux/desktop.jpg)

**Comment by edgarchinchilla** [comment]
Hi @exodius48, a new version is live now, please update as usual from [Greasyfork](https://greasyfork.org/en/scripts/6952-aptoide-market-direct-apk-downloader).

I will close this Issue, if you encounter anything else broken, please feel free to posting it!
