### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by What-Zit-Tooya** [edgarchinchilla/aptoidemarketapkdownloader#3]
Completely broken on latest aptoide mobile site

[img]http://i.imgur.com/buZs99r.png[/img]

**Comment by kiwina** [comment]
yep

**Comment by edgarchinchilla** [comment]
Hi @exodius48  and @kiwina, thanks for the notification!

There is great news, I just released a new an improved version (v9.0) of the script, that fixes the support for the new site and adds some good things...

Take a look at the full changelog: [v9.0](https://github.com/edgarchinchilla/aptoidemarketapkdownloader/releases/tag/v9.0)

I will close the Issue, if you encounter new bugs, please report it.
