### ISSUE TITLE
broken again

### ISSUE THREAD

**Issue by What-Zit-Tooya** [edgarchinchilla/aptoidemarketapkdownloader#5]
broken on aptoide mobile site , datecode today 5/25/2017

**Comment by edgarchinchilla** [comment]
Thanks for the report @exodius, I will take a look to the script ASAP, but please be patient, Right now I have a lot of work!

El 24 may. 2017 8:23 PM, Exodius Exorcist <notifications@github.com> escribió:

broken on aptoide mobile site , datecode today 5/25/2017

**Comment by edgarchinchilla** [comment]
Hi @exodius48 

The Mobile Site support has been restored again!

Please check https://github.com/edgarchinchilla/aptoidemarketapkdownloader/releases/tag/v9.5
