### ISSUE TITLE
Script broken again

### ISSUE THREAD

**Issue by What-Zit-Tooya** [edgarchinchilla/aptoidemarketapkdownloader#6]
Not showing "Download APK" on mobile site.

**Comment by edgarchinchilla** [comment]
Hi @exodius48 

Please try updating to the latest version of the script at [Aptoide Downloader v9.5.1](https://github.com/edgarchinchilla/aptoidemarketapkdownloader/releases/download/v9.5.1/aptoide.market.downloader.user.js)

¡Thanks for the report!
